namespace UIToolkitBinding.CodeEmitters;

internal class CodeEmitter_GeneratedEventArgsCache : CodeEmitter
{
    public static string Generated(EquatableArray<string> propertyNames)
    {
        Buffer.Clear();
        Buffer.AppendLine("""
// <auto-generated />
#pragma warning disable
#nullable enable

using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;

namespace UIToolkitBinding
{
    internal static class GeneratedEventArgsCache
    {
""");
        foreach (var propertyName in propertyNames)
        {
            if (string.IsNullOrEmpty(propertyName)) continue;
            Buffer.AppendLine($$"""
        internal static readonly BindablePropertyChangedEventArgs {{propertyName}} = new("{{propertyName}}");
""");
        }
        Buffer.AppendLine("""
    }
}
""");

        var result = Buffer.ToString();
        Buffer.Clear();
        return result;
    }
}
