using UIToolkitBinding.Core;

namespace UIToolkitBinding.CodeEmitters;

internal sealed class CodeEmitter_UITKDataSourceObject : CodeEmitter
{
    public static string Generate(UITKDataSourceObjectContext context)
    {
        Buffer.Clear();
        Buffer.AppendLine($$"""
// <auto-generated />
#pragma warning disable
#nullable enable

using System;
using UIToolkitBinding;
using Unity.Properties;
using UnityEngine;
using UnityEngine.UIElements;

""");
        if (!string.IsNullOrEmpty(context.Namespace))
        {
            Buffer.AppendLine($$"""
namespace {{context.Namespace}}
{
""");
        }
        Buffer.AppendLine($$"""
partial class {{context.ClassName}} : INotifyBindablePropertyChanged
{
    public event EventHandler<BindablePropertyChangedEventArgs> propertyChanged;

{{AppendProperties(context)}}
    void NotifyPropertyChanged(BindablePropertyChangedEventArgs e)
    {
        propertyChanged?.Invoke(this, e);
    }

    bool SetProperty<T>(ref T field, in T value, in BindablePropertyChangedEventArgs eventArgs)
    {
        if (EqualityComparer<T>.Default.Equals(field, value)) return false;

        field = value;
        propertyChanged?.Invoke(this, eventArgs);
        return true;
    }

{{AppendOnPropertyChangeMethods(context)}}
    internal static partial class EventArgsCache
    {
{{AppendEventArgsCacheProperties(context)}}
    }
}
""");
        if (!string.IsNullOrEmpty(context.Namespace))
        {
            Buffer.Append("""
}
""");
        }
        var result = Buffer.ToString();
        Buffer.Clear();
        return result;
    }

    static string AppendProperties(UITKDataSourceObjectContext context)
    {
        TempBuffer.Clear();
        for (int i = 0; i < context.Members.Length; i++)
        {
            var member = context.Members[i];
            TempBuffer.AppendLine($$"""
    [CreateProperty]
    {{member.DeclaredAccessibility.ToKeyword()}} {{member.Type}} {{member.PropertyName}}
    {
        get => {{member.GetFieldExpressionInGetAccessor()}};
        {{member.SetterAccessibility.ToSetterAccessorDeclaration()}}
        {
            if (global::System.Collections.Generic.EqualityComparer<{{member.Type}}>.Default.Equals({{member.GetFieldExpressionInSetAccessor()}}, value)) return;
            On{{member.PropertyName}}Changing();
            On{{member.PropertyName}}Changing(value);
            On{{member.PropertyName}}Changing({{member.GetFieldExpressionInSetAccessor()}}, value);
            var oldValue = {{member.GetFieldExpressionInSetAccessor()}};
            {{member.GetFieldExpressionInSetAccessor()}} = value;
            On{{member.PropertyName}}Changed();
            On{{member.PropertyName}}Changed(value);
            On{{member.PropertyName}}Changed(oldValue, value);
            propertyChanged?.Invoke(this, EventArgsCache.{{member.PropertyName}}Changed);
        }
    }
""");
            if (i != context.Members.Length - 1) TempBuffer.AppendLine();
        }

        var result = TempBuffer.ToString();
        TempBuffer.Clear();
        return result;
    }
    static string AppendOnPropertyChangeMethods(UITKDataSourceObjectContext context)
    {
        TempBuffer.Clear();
        foreach (var member in context.Members)
        {
            TempBuffer.AppendLine($"""
    partial void On{member.PropertyName}Changing();
    partial void On{member.PropertyName}Changing({member.Type} newValue);
    partial void On{member.PropertyName}Changing({member.Type} currentValue, {member.Type} newValue);
    partial void On{member.PropertyName}Changed();
    partial void On{member.PropertyName}Changed({member.Type} currentValue);
    partial void On{member.PropertyName}Changed({member.Type} oldValue, {member.Type} currentValue);
""");
        }
        var result = TempBuffer.ToString();
        TempBuffer.Clear();
        return result;
    }

    static string AppendEventArgsCacheProperties(UITKDataSourceObjectContext context)
    {
        TempBuffer.Clear();
        foreach (var member in context.Members)
        {

            TempBuffer.AppendLine($$"""
        internal static readonly BindablePropertyChangedEventArgs {{member.PropertyName}}Changed = new(nameof({{member.PropertyName}}));
""");

        }
        var result = TempBuffer.ToString();
        TempBuffer.Clear();
        return result;
    }
}
